services:
  - type: web
    name: newsight-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newsight-db
          property: connectionString

  - type: worker
    name: newsight-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newsight-db
          property: connectionString